---
# token is the admin_token in keystone.conf
token:    {{ admin_token }}
endpoint: http://{{ keystone_server }}:35357/v2.0

default tenant:
    name:        openstackDemo
    description: Default Tenant

# This is the admin user
default user:
    name:     adminUser
    password: secretword

# See: http://docs.openstack.org/essex/openstack-compute/install/content/setting-up-tenants-users-and-roles.html
service users:
    - name:     glance
      password: glance

    - name:     nova
      password: nova

    - name:     ec2
      password: ec2

    - name:     swift
      password: swiftpass

    - name:     cinder
      password: cinder

    - name:     quantum
      password: quantum

    - name:     volume
      password: volume

# See: http://docs.openstack.org/essex/openstack-compute/install/content/keystone-service-endpoint-create.html
services and endpoints:
    - name:         keystone
      type:         identity
      description:  Keystone Identity Service
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:5000/v2.0
      internalurl:  http://{{ keystone_server }}:5000/v2.0
      adminurl:     http://{{ keystone_server }}:35357/v2.0

    - name:         nova
      type:         compute
      description:  Nova Compute Service
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:8774/v2/%(tenant_id)s
      internalurl:  http://{{ keystone_server }}:8774/v2/%(tenant_id)s
      adminurl:     http://{{ keystone_server }}:8774/v2/%(tenant_id)s

    - name:         volume
      type:         volume
      description:  Nova Volume Service
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:8776/v1/%(tenant_id)s
      internalurl:  http://{{ keystone_server }}:8776/v1/%(tenant_id)s
      adminurl:     http://{{ keystone_server }}:8776/v1/%(tenant_id)s

    - name:         glance
      type:         image
      description:  Glance Image Service
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:9292/v1
      internalurl:  http://{{ keystone_server }}:9292/v1
      adminurl:     http://{{ keystone_server }}:9292/v1

    - name:         ec2
      type:         ec2
      description:  EC2 Compatibility Layer
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:8773/services/Cloud
      internalurl:  http://{{ keystone_server }}:8773/services/Cloud
      adminurl:     http://{{ keystone_server }}:8773/services/Admin

    - name:         swift
      type:         object-store
      description:  Swift Object Storage Service
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:8888/v1/AUTH_%(tenant_id)s
      internalurl:  http://{{ keystone_server }}:8888/v1/AUTH_%(tenant_id)s
      adminurl:     http://{{ keystone_server }}:8888/v1


    - name:         cinder
      type:         volume
      description:  Cinder Volume Storage Service
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:8776/v1/%(tenant_id)s
      internalurl:  http://{{ keystone_server }}:8776/v1/%(tenant_id)s
      adminurl:     http://{{ keystone_server }}:8888/v1

    - name:         quantum
      type:         network
      description:  Quantum Network Service
      region:       RegionOne
      publicurl:    http://{{ keystone_server }}:9696/v2
      internalurl:  http://{{ keystone_server }}:9696/v2
      adminurl:     http://{{ keystone_server }}:9696/v2
