---
# token is the admin_token in keystone.conf
token:    {{ admin_token }}
endpoint: http://192.168.206.130:35357/v2.0

default tenant:
    name:        openstackDemo
    description: Default Tenant

# This is the admin user
default user:
    name:     adminUser
    password: secretword

# See: http://docs.openstack.org/essex/openstack-compute/install/content/setting-up-tenants-users-and-roles.html
service users:
    - name:     glance
      password: glance

    - name:     nova
      password: nova

    - name:     ec2
      password: ec2

    - name:     swift
      password: swiftpass

# See: http://docs.openstack.org/essex/openstack-compute/install/content/keystone-service-endpoint-create.html
services and endpoints:
    - name:         keystone
      type:         identity
      description:  Keystone Identity Service
      region:       RegionOne
      publicurl:    http://192.168.206.130:5000/v2.0
      internalurl:  http://192.168.206.130:5000/v2.0
      adminurl:     http://192.168.206.130:35357/v2.0

    - name:         nova
      type:         compute
      description:  Nova Compute Service
      region:       RegionOne
      publicurl:    http://192.168.206.130:8774/v2/%(tenant_id)s
      internalurl:  http://192.168.206.130:8774/v2/%(tenant_id)s
      adminurl:     http://192.168.206.130:8774/v2/%(tenant_id)s

    - name:         volume
      type:         volume
      description:  Nova Volume Service
      region:       RegionOne
      publicurl:    http://192.168.206.130:8776/v1/%(tenant_id)s
      internalurl:  http://192.168.206.130:8776/v1/%(tenant_id)s
      adminurl:     http://192.168.206.130:8776/v1/%(tenant_id)s

    - name:         glance
      type:         image
      description:  Glance Image Service
      region:       RegionOne
      publicurl:    http://192.168.206.130:9292/v1
      internalurl:  http://192.168.206.130:9292/v1
      adminurl:     http://192.168.206.130:9292/v1

    - name:         ec2
      type:         ec2
      description:  EC2 Compatibility Layer
      region:       RegionOne
      publicurl:    http://192.168.206.130:8773/services/Cloud
      internalurl:  http://192.168.206.130:8773/services/Cloud
      adminurl:     http://192.168.206.130:8773/services/Admin

    - name:         swift
      type:         object-store
      description:  Swift Object Storage Service
      region:       RegionOne
      publicurl:    http://192.168.206.130:8888/v1/AUTH_%(tenant_id)s
      internalurl:  http://192.168.206.130:8888/v1/AUTH_%(tenant_id)s
      adminurl:     http://192.168.206.130:8888/v1
